<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MPCustom.Core\MPCustom.Core.csproj" />
    <ProjectReference Include="..\MPCustom.Security\MPCustom.Security.csproj" />
    <ProjectReference Include="..\MPCustom.Network\MPCustom.Network.csproj" />
    <ProjectReference Include="..\MPCustom.ErrorPage\MPCustom.ErrorPage.csproj" />
  </ItemGroup>

</Project>
